backend:
  name: git-gateway
  branch: main   # change if your repo branch is not "main"

media_folder: "public/uploads"   # where images get saved in your repo
public_folder: "/uploads"        # how they are shown on the site

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"   # location of your blog posts
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "pubDate", label: "Publish Date", widget: "datetime" }
      - { name: "heroImage", label: "Hero Image", widget: "image", required: false }
      - { name: "badge", label: "Badge", widget: "string", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "body", label: "Content", widget: "markdown" }
